/*    
CloudTrail Log Viewer, is a Java desktop application for reading AWS CloudTrail
logs files.

Copyright (C) 2015  Mark P. Haskins

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

package com.haskins.jcloudtrailerviewer.event;

import com.haskins.jcloudtrailerviewer.model.Event;
import java.util.List;

/**
 * Should be implemented by any class that needs to know what the EventLoader
 * is doing.
 * 
 * @author mark.haskins
 */
public interface EventLoaderListener {
    
    /**
     * Called when a new batch of Events have been loaded.
     * @param events 
     */
    public void newEvents(List<Event> events);
    
    /**
     * Called when a new String message has been generated by the EventLoader.
     * @param message 
     */
    public void newMessage(String message);
    
    /**
     * Called when all files has been loaded and processed.
     */
    public void finishedLoading();
}
